aller musee.
aller etage.
parler.
aller musee.
aller fusee.
aller espace.
aller soleil.
aller fusee.
aller espace.
aller soleil.
aller fusee.
aller espace.
aller station_solaire.
aller entree.
voir bureau.
aller tarmac.
aller fusee.
aller espace.
aller leviathe.
aller plafond.
voir terminal.
aller module_controle.
aller dehors.
aller fusee.
aller espace.
aller soleil.
aller fusee.
aller espace.
aller sabliere.
aller trappe.
aller projet.
aller salle.
prendre generateur.
aller ascenseur.
aller surface.
aller dehors.
aller fusee.
aller espace.
aller oeil_univers.